// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4SDtWzTTY_2FkWrdNxqKwzOV-QwkvY2c',
    appId: '1:1062275798598:web:88956f58816ba663021c47',
    messagingSenderId: '1062275798598',
    projectId: 'packagedeliveryapp-3fb65',
    authDomain: 'packagedeliveryapp-3fb65.firebaseapp.com',
    storageBucket: 'packagedeliveryapp-3fb65.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKA7NJQCVFC4QdDwI0lSh1PrkiAzeokK4',
    appId: '1:1062275798598:android:f934c06c0d6c1662021c47',
    messagingSenderId: '1062275798598',
    projectId: 'packagedeliveryapp-3fb65',
    storageBucket: 'packagedeliveryapp-3fb65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc4z2epnuX3h04f_9-n9mF7PDSCAxOqEo',
    appId: '1:1062275798598:ios:c0d2f40a064a701a021c47',
    messagingSenderId: '1062275798598',
    projectId: 'packagedeliveryapp-3fb65',
    storageBucket: 'packagedeliveryapp-3fb65.firebasestorage.app',
    iosBundleId: 'com.example.packageDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc4z2epnuX3h04f_9-n9mF7PDSCAxOqEo',
    appId: '1:1062275798598:ios:c0d2f40a064a701a021c47',
    messagingSenderId: '1062275798598',
    projectId: 'packagedeliveryapp-3fb65',
    storageBucket: 'packagedeliveryapp-3fb65.firebasestorage.app',
    iosBundleId: 'com.example.packageDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4SDtWzTTY_2FkWrdNxqKwzOV-QwkvY2c',
    appId: '1:1062275798598:web:3800b199b418a30e021c47',
    messagingSenderId: '1062275798598',
    projectId: 'packagedeliveryapp-3fb65',
    authDomain: 'packagedeliveryapp-3fb65.firebaseapp.com',
    storageBucket: 'packagedeliveryapp-3fb65.firebasestorage.app',
  );
}
